language: php

php:
  - 5.6
  - 7.2
  - 7.4
  - nightly

compiler:
  - clang
  - gcc

before_install:
  - pass=$(perl -e 'print crypt("password", "testuser")')
  - sudo useradd -m -p "$pass" testuser
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsmbclient-dev samba
  - sudo bash tests/setup-share.sh
  - |
    echo "
    [testshare]
    comment = testshare
    path = /home/testuser/testshare
    guest ok = no
    read only = no
    map archive = yes
    map system = yes
    map hidden = yes
    create mask = 0777
    inherit permissions = yes
    " | sudo tee -a /etc/samba/smb.conf
  - sudo service smbd restart
  - testparm -s
  - ( echo password; echo password ) | sudo smbpasswd -s -a testuser
  - php --version | egrep 'PHP [57]' &>/dev/null && wget https://phar.phpunit.de/phpunit-5.phar -O phpunit.phar || wget https://phar.phpunit.de/phpunit-nightly.phar -O phpunit.phar

script:
  - phpize
  - ./configure
  - make
  - sudo make install
  - php --define extension="smbclient.so" phpunit.phar --verbose --testsuite php$(php --version | grep 'PHP 8' &>/dev/null && echo '8')
